server:
  port: 9002

logging:
  level:
    org.springframework: ERROR
    com.microservice.user: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log